### ISSUE TITLE
Annotation on method is removed by Kilim Weaver

### ISSUE THREAD

**Issue by JasonHuangHuster** [kilim/kilim#53] opened 2017-07-06 05:59 UTC
i have annotations on class name and method also , after kilim weaver only annotation on class is keeped , but annotation on method is gone .

`
   @RpcService(value = "javasvr_ckv_cdb", modid = 670209, cmdid = 232072, routeIp = "")
public interface CkvCdbChain {

    @RpcCmd(value = "Add", retry = 2, timeout = 400)
    EduCkvChainMsg.AddRsp  addEntry(EduCkvChainMsg.AddReq addReq)throws Pausable,APIException;

    @RpcCmd(value = "Del", retry = 2, timeout = 400)
    EduCkvChainMsg.DelRsp  delEntry(EduCkvChainMsg.DelReq delReqReq)throws Pausable,APIException;

    @RpcCmd(value = "GetOne", retry = 2, timeout = 400)
    EduCkvChainMsg.GetOneRsp  getOne(EduCkvChainMsg.GetOneReq getOneReq)throws Pausable,APIException;

    @RpcCmd(value = "Mod", retry = 2, timeout = 400)
    EduCkvChainMsg.ModRsp  modEnry(EduCkvChainMsg.ModReq modReq)throws Pausable,APIException;

    @RpcCmd(value = "GetList", retry = 2, timeout = 400)
    EduCkvChainMsg.GetListRsp  getList(EduCkvChainMsg.GetListReq getListReq)throws Pausable,APIException;

    @RpcCmd(value = "MultiGetList", retry = 2, timeout = 400)
    EduCkvChainMsg.MultiGetListRsp multiGetList(EduCkvChainMsg.MultiGetListReq multiGetListReq) throws Pausable, APIException;

    @RpcCmd(value = "GetReverseList", retry = 2, timeout = 400)
    EduCkvChainMsg.GetReverseListRsp getReverseList(EduCkvChainMsg.GetReverseListReq getReverseListReq) throws Pausable,APIException;
}
`

need help here , tks advance . :)

**Comment by nqzero** [comment] 2017-07-06 15:30
i'm able to reproduce this - i'll investigate

**Comment by nqzero** [comment] 2017-07-06 16:54
here's a patch that appears to fix the problem. i need to spend some time thinking about if this can break anything else. @kilim does this look safe to you ?
```
diff --git a/src/kilim/analysis/MethodWeaver.java b/src/kilim/analysis/MethodWeaver.java
index f7d21ac..e35466b 100755
--- a/src/kilim/analysis/MethodWeaver.java
+++ b/src/kilim/analysis/MethodWeaver.java
@@ -110,7 +110,7 @@ public class MethodWeaver {
                 mf.accept(mv);
             }
         } else {
-        	mv.visitEnd();
+        	mf.accept(mv);
         }
     }
```

@JasonHuangHuster which version of kilim are you using ? eg https://github.com/nqzero/kilim (nominally kilim 2.0), the maven version (org.db4j:kilim), or this one

**Comment by nqzero** [comment] 2017-07-06 19:38
i committed to my master (with a test)

https://github.com/nqzero/kilim/commit/9e762636941443d16d455c3aa743abb5c2a8b8e0

**Comment by JasonHuangHuster** [comment] 2017-07-07 03:22
our team use this [https://github.com/kilim/kilim/](sriram's original Kilim) and some modify have been made .
But i have checked the `MethodWeaver.class` ,our version is the same with srisam's master , i didn't  modify it , I've made a compare with your version [https://github.com/nqzero/kilim](nqzero kilim) , there's lots of changes , i think before we use kilim 2.0 , we would have to run a solid tests . so it's better to apply this modify first .
tks for you help ! i hope our team could move to the kilim 2.0 as soon as possible.

**Comment by JasonHuangHuster** [comment] 2017-07-07 05:40
hi , i've tested the patch , it seems you just modify one line , so i replace that with srisam's `MethodWeaver.class` version , if fixed the annotation problem , but it brings another , the static inner class won't be weaved properly .

**Comment by nqzero** [comment] 2017-07-07 11:45
I don't have access to a computer at the moment, but it's possible that is
fixed in my fork (I fixed many bugs with the Weaver). Check the log - You
may be able to cherry pick a single commit. If not I will be back online
sometime this afternoon



On Jul 7, 2017 1:40 AM, "Adams.H" <notifications@github.com> wrote:

hi , i've tested the patch , it seems you just modify one line , so i
replace that with srisam's MethodWeaver.class version , if fixed the
annotation problem , but it brings another , the static inner class won't
be weaved properly .

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/kilim/kilim/issues/53#issuecomment-313591910>, or mute
the thread

**Comment by nqzero** [comment] 2017-07-22 17:27
this patch is released in the maven central repository at org.db4j:kilim:2.0.0-12

**Comment by JasonHuangHuster** [comment] 2017-11-21 04:43
hi @nqzero  this problem happens again ... when i use root to maven package , the annotation is kept correctly , but when i use a non-root user to maven package , the annotation on method is lost again ... 
i use `mvn clean package -U -X` to avoid any cache .



[educi.txt](https://github.com/kilim/kilim/files/1490057/educi.txt)
[root.txt](https://github.com/kilim/kilim/files/1490058/root.txt)

is kilim weave must a root user operation ?

**Comment by nqzero** [comment] 2018-01-26 04:52
during weaving, the original method is modified by adding a fiber argument and a new placeholder method is created with the original signature. in at least java 7, runtime annotations are not duplicated for the placeholder method. it's possible that this issue affects java 8 in some other cases

for now, this issue is considered low priority - as a workaround, look up the annotations using the fiber-enabled variant. if anyone has a use-case where this workaround isn't viable, please post an example

this limitation is documented in 54247ff0ac4d35d21f79916218df4044533ab968

**Comment by nqzero** [comment] 2018-09-28 00:33
i've spoken with sriram and we think that it would be better to duplicate the annotation instead of moving it to the women method. this enhancement is currently low priority - comment or give this note a thumbs up if it's a priority for you

**Closed** 2018-10-03 18:10 UTC
