### ISSUE TITLE
"ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0" in kilim.Mailbox

### ISSUE THREAD

**Issue by forchid** [kilim/kilim#71] opened 2020-09-13 14:16 UTC
# the issue
```java
$ java -Dkilim.Scheduler.numThreads=1 -Ddebug=true ChanPerfKilim 0 10
[main] size 0, items 10
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at kilim.Mailbox.put(Mailbox.java:134)
	at kilim.Mailbox.put(Mailbox.java:372)
	at ChanPerfKilim$Writer.execute(ChanPerfKilim.java:56)
	at kilim.Task.run(Task.java:550)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at kilim.Mailbox.get(Mailbox.java:80)
	at kilim.Mailbox.get(Mailbox.java:169)
	at ChanPerfKilim$Reader.execute(ChanPerfKilim.java:74)
	at kilim.Task.run(Task.java:550)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
33ms
```

# the test case
```java
import kilim.*;
import kilim.tools.*;

public class ChanPerfKilim {

  static final boolean debug = Boolean.getBoolean("debug");

  public static void main(String[] args) throws Exception {
    if (Kilim.trampoline(new Object() {},false,args)) return;
    
    final int size, items;
    
    if (args.length > 0) size = Integer.decode(args[0]);
    else size = 0;
    if (args.length > 1) items = Integer.decode(args[1]);
    else items = 10000000;
    log("size %d, items %d", size, items);
    
    final Mailbox<Integer> chan;
    if (size < 1) chan = new Mailbox<>(0, 1);
    else chan = new Mailbox<>(size, size);

    Mailbox<ExitMsg<?>> exitmb1 = new Mailbox<>();
    Mailbox<ExitMsg<?>> exitmb2 = new Mailbox<>();
    
    Task writer = new Writer(chan, items);
    writer.informOnExit(exitmb1);

    Task reader = new Reader(chan, items);
    writer.informOnExit(exitmb2);

    long ts = System.currentTimeMillis();
    writer.start();
    reader.start();

    exitmb1.getb();
    exitmb2.getb();
    long te = System.currentTimeMillis();
    
    System.out.println((te - ts) + "ms");
  }

  static class Writer extends Task {
    Mailbox<Integer> mymb;
    final int n;

    public Writer(Mailbox<Integer> mymb, int n) {
      this.mymb = mymb;
      this.n = n;
    }

    public void execute() throws Pausable {
      int i = n;
      do {
        int j = --i;
        mymb.put(j);
        log("put(): %d", j);
      } while (0 < i);
    }
  }

  static class Reader extends Task {
    Mailbox<Integer> mymb;
    final int n;

    public Reader(Mailbox<Integer> mymb, int n) {
      this.mymb = mymb;
      this.n = n;
    }

    public void execute() throws Pausable {
      int i = n;
      do {
        int j = mymb.get();
        log("get(): %d", j);
        --i;
      } while (0 < i);
    }
  }

  static void log(String format, Object ...args) {
    if (debug) {
      String threadName = Thread.currentThread().getName();
      String s = String.format(format, args);
      System.out.println(String.format("[%s] %s", threadName, s));
    }
  }

}
```

**Comment by nqzero** [comment] 2020-10-04 03:28
I can reproduce this bug. 0-size Mailboxes don't really make sense in kilim. not sure if I should fix the reallocation, or just set the minimum size to 1 in the constructor

@sriram-srinivasan see any disadvantage to setting the min size for a Mailbox to 1 ?

in terms of the performance, looks like what you're trying to do is similar to this ring buffer test that we helped optimize a bit a couple years ago

https://github.com/vy/fiber-test

if you did any benchmarking of kilim vs other implementations, would be interested in seeing the results. also, I see that you're using github.com/offbynull/coroutines which I had not previously seen. If you can share any lessons learned or advantages of one vs the other, that would be great too !

thanks for checking out kilim !

**Comment by sriram-srinivasan** [comment] 2020-10-04 10:44
> @sriram-srinivasan <https://github.com/sriram-srinivasan> see any disadvantage to setting the min size for a Mailbox to 1 ?
> in terms of the performance, looks like what you're trying to do is similar to this ring buffer test that we helped optimize a bit a couple years ago
> 
No, it is worth setting it to 1. Let mailbox always stand for buffered I/O.

**Comment by nqzero** [comment] 2020-10-04 19:34
@sriram-srinivasan do you think the unbuffered variant that Peter proposed in 72 seems like a feature worth adding ? ie, is it a commonly used golang metaphor ? if so, any thoughts on a name ?

not immediately obvious to me what the use case would be - ie, why bother waiting for another computation to reach a particular point if you don't care about the result of the computation

**Comment by forchid** [comment] 2020-10-09 04:50
We should make sure that the min size of a mailbox is 1 if no unbuffered mailbox in kilim.

**Comment by nqzero** [comment] 2020-10-25 03:33
this is closed by:
https://github.com/nqzero/kilim/commit/3248c9fd48c44c9cfb3d501ece1753bff1752898

thanks for the bug report @little-pan !

**Closed as completed by nqzero** 2020-10-25 03:33 UTC
