### ISSUE TITLE
Problem with version 2.0.1

### ISSUE THREAD

**Issue by yuqi1129** [kilim/kilim#62] opened 2019-12-06 13:10 UTC
Environment:

JDK: 
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
OS: MacOS 10.13.1

Code:
```
public class Server extends Task {

    private Mailbox<Long> mailbox;

    public Server(Mailbox<Long> mailbox) {
        this.mailbox = mailbox;
    }

    @Override
    public void execute() throws Pausable, Exception {
        //super.execute();
        try {
            while (true) {
                mailbox.putnb(System.currentTimeMillis() / 1000L);

                Task.sleep(2000L);
                if (mailbox.hasMessage()) {
                    System.out.println("receive data from client:'" + mailbox.getnb() + "'");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

public class Client extends Task {
    private Mailbox<Long> mailbox;

    public Client(Mailbox<Long> mailbox) {
        this.mailbox = mailbox;
    }

    @Override
    public void execute() throws Pausable, Exception {

        try {
            while (true) {
                if (mailbox.hasMessage()) {
                    System.out.println("receive data from server:'" + mailbox.getnb() + "'");
                }

                Task.sleep(1000);
                mailbox.putnb(System.currentTimeMillis() / 1000L);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

public class Main {
    public static void main(String[] args) {

        Mailbox<Long> mailbox = new Mailbox<>();
        Client client = new Client(mailbox);
        Server server = new Server(mailbox);

        client.start();
        server.start();
    }
}
```
Kilim version
2.0.1

When running main in Main, it outputs nothings buts it works well with kilim 2.0.0-25
see below
2.0.1
![image](https://user-images.githubusercontent.com/15794564/70325169-5df39300-186c-11ea-9517-0f53998bcb6f.png)

2.0.0-25
![image](https://user-images.githubusercontent.com/15794564/70325378-cc385580-186c-11ea-872e-f23bad67900d.png)

**Comment by nqzero** [comment] 2019-12-06 17:34
Hi @yuqi1129 

The current behavior is correct. I believe that has changed is that the scheduler threads are now set as "daemon", allowing the jvm to exit once main completes. You can fix this by adding `server.joinb()` to main.

There's also `Scheduler.getDefaultScheduler().idledown()` which for quick demos is very useful which watches all Tasks the scheduler knows about and exits when nothing is happening. But that's a heuristic, so for a real application it's better to use `Task.joinb` or `Mailbox.getb`.

A couple other notes about your example. You're using `putnb` and `getnb` inside `Pausable` code. Those methods are non-blocking so they're not reliable (which is ok in your case because you're wrapping them in a loop). You can replace them with the `Pausable` variants, ie `put` and `get` and everything should just work.

If you create a github repo for your example, I'll do a pull request (add a comment in this issue linking to it)

**Comment by nqzero** [comment] 2019-12-06 17:36
closing this issue as it's not a bug but i'll continue to respond to this thread so feel free to ask additional questions (I should get notifications).

**Closed by nqzero** 2019-12-06 17:36 UTC

**Comment by yuqi1129** [comment] 2019-12-07 08:07
@nqzero I see, thanks for your answer
